//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Statement
    {
        public int IdStatement { get; set; }
        public string Worker { get; set; }
        public string PassportDeclarant { get; set; }
        public string FamilyInn { get; set; }
        public string FamilyInn1 { get; set; }
        public string FamilyInn2 { get; set; }
        public string FamilyInn3 { get; set; }
        public string FamilyInn4 { get; set; }
        public string FamilyInn5 { get; set; }
        public string StatusStatement { get; set; }
    
        public virtual Declarant Declarant { get; set; }
        public virtual Status Status { get; set; }
        public virtual WorkerMfc WorkerMfc { get; set; }
    }
}
