//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declarant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Declarant()
        {
            this.C_Statement = new HashSet<C_Statement>();
        }
    
        public string PassportDeclarant { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Surname { get; set; }
        public string Telephone { get; set; }
        public System.DateTime DateOfbirth { get; set; }
        public string SocialStatus { get; set; }
        public string IdSingleHousingDocument { get; set; }
        public string ActualAddressOfResidence { get; set; }
        public string RegistrationAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Statement> C_Statement { get; set; }
        public virtual SocialStatus SocialStatus1 { get; set; }
    }
}
