//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocFondEntities : DbContext
    {
        public SocFondEntities()
            : base("name=SocFondEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Statement> C_Statement { get; set; }
        public virtual DbSet<Declarant> Declarant { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<SocialStatus> SocialStatus { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<WorkerMfc> WorkerMfc { get; set; }
    }
}
